name: CI Docs
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'packages/twenty-docs/**'
      - 'packages/twenty-ui/**'
  pull_request:
    paths:
      - 'package.json'
      - 'packages/twenty-docs/**'
      - 'packages/twenty-ui/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Docs / Build Documentation
        run: npx nx build twenty-docs
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.directories.outputs.LIST }}
          fail_on_error: true
          vale_flags: "--minAlertLevel=error"
          reporter: github-pr-check
          token: ${{ github.token }}
          filter_mode: nofilter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
